import { useEffect, useMemo, useState } from 'react';
import { authors, chapters, image, quiz, timeline } from './data/edition';

const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });

function Masthead() {
  const [compact, setCompact] = useState(false);
  const [progress, setProgress] = useState(0);
  useEffect(() => {
    const update = () => { setCompact(scrollY > 80); setProgress(Math.round(scrollY / Math.max(1, document.body.scrollHeight - innerHeight) * 100)); };
    update(); addEventListener('scroll', update, { passive: true }); return () => removeEventListener('scroll', update);
  }, []);
  return <header className={`masthead ${compact ? 'compact' : ''}`}>
    <button className="wordmark" onClick={() => scrollTo('capa')} aria-label="Voltar à capa">PANORAMA</button>
    <nav aria-label="Navegação principal"><button onClick={() => scrollTo('sumario')}>SUMÁRIO</button><button onClick={() => scrollTo('galeria')}>EXPLORAR</button></nav>
    <span className="edition">BARILOCHE <i>2026</i></span><div className="reading-progress" style={{ transform: `scaleX(${progress / 100})` }} />
  </header>;
}

function Lightbox({ index, close }: { index: number; close: () => void }) {
  const [current, setCurrent] = useState(index);
  useEffect(() => { const keys = (e: KeyboardEvent) => { if (e.key === 'Escape') close(); if (e.key === 'ArrowRight') setCurrent(v => (v + 1) % 100); if (e.key === 'ArrowLeft') setCurrent(v => (v + 99) % 100); }; addEventListener('keydown', keys); return () => removeEventListener('keydown', keys); }, [close]);
  return <div className="lightbox" role="dialog" aria-modal="true" aria-label="Visualizador de fotos" onMouseDown={close}><button className="close" onClick={close}>FECHAR ×</button><button className="arrow left" onMouseDown={e => e.stopPropagation()} onClick={() => setCurrent(v => (v + 99) % 100)} aria-label="Foto anterior">←</button><figure onMouseDown={e => e.stopPropagation()}><img src={image(current + 1)} alt={`Registro da viagem a Bariloche, foto ${current + 1} de 100`} /><figcaption>{String(current + 1).padStart(2, '0')} / 100 — Bariloche 2026</figcaption></figure><button className="arrow right" onMouseDown={e => e.stopPropagation()} onClick={() => setCurrent(v => (v + 1) % 100)} aria-label="Próxima foto">→</button></div>;
}

function Budget() {
  const [money, setMoney] = useState(1850); const [days, setDays] = useState(7); const [rate, setRate] = useState(260); const [reserve, setReserve] = useState(400);
  const free = Math.max(0, money - reserve); const converted = free * rate;
  return <section id="matematica" className="math section"><p className="eyebrow">07 — DADOS DE VIAGEM</p><h2>Matemática<br />da viagem</h2><div className="math-feature"><div><span className="math-number">R$ 1.850</span><p>Um exemplo de divisão usado na edição: R$ 800 para gastos livres, R$ 400 como reserva e R$ 650 para taxas/atividades.</p><div className="bar"><b style={{ width: '43%' }}>LIVRE</b><b style={{ width: '22%' }}>RESERVA</b><b style={{ width: '35%' }}>FIXOS</b></div></div><div className="equation">R$ 800 × 260<br /><strong>= 208.000 pesos</strong><br /><small>208.000 ÷ 7 = 29.714 pesos/dia</small></div></div><div className="simulator"><div><p className="eyebrow">E SE FOSSE A SUA VIAGEM?</p><h3>Seu cenário, sem promessa de cotação.</h3><label>Orçamento disponível <output>R$ {money.toLocaleString('pt-BR')}</output><input type="range" min="500" max="8000" step="50" value={money} onChange={e => setMoney(+e.target.value)} /></label><label>Dias <output>{days}</output><input type="range" min="3" max="15" value={days} onChange={e => setDays(+e.target.value)} /></label><label>Cotação peso/real <input value={rate} type="number" onChange={e => setRate(+e.target.value || 0)} /></label><label>Reserva <input value={reserve} type="number" min="0" onChange={e => setReserve(+e.target.value || 0)} /></label></div><div className="result"><span>ORÇAMENTO LIVRE</span><strong>R$ {free.toLocaleString('pt-BR')}</strong><span>CONVERTIDO</span><strong>{converted.toLocaleString('pt-BR')} pesos</strong><span>MÉDIA POR DIA</span><strong>{Math.round(converted / days).toLocaleString('pt-BR')} pesos</strong><small>A cotação da viagem não representa a cotação atual. Ajuste o valor manualmente.</small></div></div></section>;
}

function Passport() {
  const [answers, setAnswers] = useState<number[]>(() => JSON.parse(localStorage.getItem('panorama-passport') || '[]'));
  const done = answers.length; const profile = useMemo(() => answers.filter(n => n === 1).length >= 3 ? ['EXPLORADOR DA NEVE', 'Acordaria cedo mesmo depois de dormir pouco. Se tem frio, teleférico ou montanha, você está dentro.'] : answers.filter(n => n === 0).length >= 3 ? ['CAÇADOR DE MEMÓRIAS', 'Seu armazenamento acabaria antes da viagem — e você saberia exatamente onde todo mundo estava em cada momento.'] : ['GUIA NÃO OFICIAL', 'Você lê o cronograma, organiza os amigos e ainda lembra alguém de levar o casaco.']);
  const pick = (q: number, option: number) => { const next = [...answers]; next[q] = option; setAnswers(next); localStorage.setItem('panorama-passport', JSON.stringify(next)); };
  const share = async () => { const text = `Meu perfil em Bariloche é ${profile[0]} — PANORAMA 2026`; if (navigator.share) await navigator.share({ title: 'Passaporte Panorama', text }); else await navigator.clipboard?.writeText(text); };
  return <section id="passaporte" className="passport section"><p className="eyebrow">09 — PASSAPORTE PANORAMA <span>{done}/5</span></p><h2>Que tipo de viajante<br />você seria?</h2><p className="intro">Cinco escolhas, feitas só aqui no seu navegador. Sem login, sem coleta.</p><div className="passport-grid">{quiz.map(([question, options], q) => <fieldset key={question}><legend>{String(q + 1).padStart(2, '0')} — {question}</legend>{options.map((option, i) => <button key={option} className={answers[q] === i ? 'selected' : ''} onClick={() => pick(q, i)}>{String.fromCharCode(65 + i)} — {option}</button>)}</fieldset>)}</div>{done === 5 && <div className="profile"><p>SEU PASSAPORTE</p><h3>{profile[0]}</h3><p>{profile[1]}</p><button onClick={share}>COMPARTILHAR MEU PERFIL ↗</button><button onClick={() => { setAnswers([]); localStorage.removeItem('panorama-passport'); }}>REFAZER</button></div>}</section>;
}

export default function App() {
  const [photo, setPhoto] = useState<number | null>(null); const [openDay, setOpenDay] = useState<number | null>(null);
  return <><Masthead /><main>
    <section id="capa" className="hero"><img src={image(1)} fetchPriority="high" alt="Grupo em Bariloche sob o céu de inverno" /><div className="hero-copy"><p>EDITORA EPIFANIA · AGOSTO 2026 · EDIÇÃO Nº 1</p><h1>BARILOCHE</h1><h2>Por que sua formatura merece essa viagem</h2><button onClick={() => scrollTo('sumario')}>ROLE PARA COMEÇAR ↓</button></div><p className="hero-footer">UMA VIAGEM. CINCO OLHARES. NOVE DIAS. HISTÓRIAS DEMAIS PARA CABER NO PAPEL.</p></section>
    <section id="sumario" className="contents section"><p className="eyebrow">A EDIÇÃO</p><h2>Sumário</h2><div>{chapters.map(([n, title, desc, id], i) => <button key={id} onClick={() => scrollTo(id)} onMouseEnter={() => setPhoto((i * 11) % 100)}><span>{n}</span><strong>{title}</strong><small>{desc}</small></button>)}</div>{photo !== null && <img className="contents-preview" src={image(photo + 1)} alt="Prévia de capítulo" />}</section>
    <section id="editorial" className="editorial section"><p className="eyebrow">01 — ABERTURA</p><h2>Editorial</h2><div className="editorial-text"><p>Algumas histórias pedem mais que uma página. Esta é uma delas: uma viagem feita de neve, ônibus, quartos compartilhados, cidade, música, cansaço e um jeito novo de olhar para quem estava por perto.</p><p>Esta edição não tenta guardar tudo. Ela escolhe os momentos que explicam por que nove dias podem continuar depois que o avião pousa.</p></div><aside><p>QUEM FEZ ESTA EDIÇÃO</p>{authors.map((author, i) => <div key={author}><img src={image(22 + i)} alt="" /><span>{author}</span><small>Relato e edição</small></div>)}</aside></section>
    <article id="materia" className="feature"><div className="feature-heading"><p className="eyebrow">02 — REPORTAGEM PRINCIPAL</p><h2>Entre a neve<br />e o fim de um ciclo</h2><p className="deck">Em Bariloche, a turma não apenas saiu da escola: aprendeu a se enxergar fora dela.</p></div><figure className="bleed"><img src={image(12)} alt="Paisagem de inverno em Bariloche" loading="lazy" /><figcaption>Frio, altitude e uma paisagem que muda o ritmo de qualquer dia.</figcaption></figure><div className="longread"><p>A viagem começou antes do avião decolar. No aeroporto, com documentos conferidos, malas, espera e a expectativa de encontrar os amigos, a história já tinha começado.</p><p>Depois vieram a cidade, o hotel, os ônibus e o primeiro choque de frio. Cada passeio parecia grande, mas foram os intervalos — uma conversa no quarto, uma caminhada sem pressa, alguém emprestando um casaco — que deram dimensão ao que estava acontecendo.</p></div><blockquote>“Em Bariloche, a turma não apenas saiu da escola: aprendeu a se enxergar fora dela.”</blockquote><div className="two-images"><img src={image(17)} loading="lazy" alt="Turma aproveitando a neve" /><div><p className="eyebrow">A PAUSA</p><p>Quando a montanha ficava encoberta, a neve, a chuva fina e o chão molhado deixavam todo mundo cansado. Era, ainda assim, o tipo bom de cansaço.</p></div><img src={image(29)} loading="lazy" alt="Amigos reunidos durante a viagem" /></div></article>
    <section id="cidade" className="city section"><p className="eyebrow">03 — BARILOCHE ALÉM DA NEVE</p><h2>O estrangeiro começa<br />nos detalhes.</h2><img src={image(57)} loading="lazy" alt="Vista do lago Nahuel Huapi" /><div className="city-notes">{[['NA RUA', 'Mitre, vitrines e a liberdade de escolher onde entrar.'], ['NA COMIDA', 'Café quente, chocolate e um croissant entre caminhadas.'], ['NO LAGO', 'Nahuel Huapi apareceu azul quando o céu finalmente abriu.'], ['NO QUARTO', 'Sete pessoas, um banheiro e histórias que não cabem em cronograma.']].map(([title, text]) => <div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section id="dias" className="timeline section"><p className="eyebrow">04 — CRONOLOGIA</p><h2>Nove dias<br />em Bariloche</h2><p className="intro">Nove dias, muitas histórias e uma viagem que passou rápido demais.</p><ol>{timeline.map(([day, title, text, img], i) => <li key={day}><button onClick={() => setOpenDay(openDay === i ? null : i)} aria-expanded={openDay === i}><span>DIA {day}</span><h3>{title}</h3><p>{text}</p><b>{openDay === i ? 'FECHAR −' : 'VER MAIS + '}</b></button>{openDay === i && <div className="day-detail"><img src={image(img)} alt={`Foto do dia ${day}`} loading="lazy" /><p>Um registro da viagem para acompanhar este capítulo. As histórias seguem em fotos, conversas e memórias compartilhadas.</p></div>}</li>)}</ol></section>
    <section id="roteiro" className="reality section"><p className="eyebrow">05 — O QUE O ROTEIRO NÃO CONTA</p><h2>Expectativa<br /><i>×</i> realidade</h2><div>{[['DESCANSO', '“Vou descansar e aproveitar tudo.”', 'Passeios de dia e festas à noite deixavam pouco espaço para dormir.'], ['NEVE', '“Vai ser só bonito.”', 'É bonita, sim. E também molhada, fria e ótima para cair.'], ['FESTAS', '“Vou só dar uma passada.”', 'A preparação no quarto já era parte da festa.'], ['ROTEIRO', '“Vou seguir tudo certinho.”', 'Os melhores momentos também apareciam nos intervalos.']].map(([title, expectation, reality]) => <details key={title}><summary><span>{title}</span><strong>EXPECTATIVA</strong><p>{expectation}</p></summary><div><strong>REALIDADE</strong><p>{reality}</p></div></details>)}</div></section>
    <section id="guia" className="guide section"><p className="eyebrow">06 — SERVIÇO</p><h2>Guia de sobrevivência<br />em Bariloche</h2><div className="tips">{['Não subestime o frio', 'Deixe espaço na mala', 'Compare o câmbio', 'Tenha um lugar fixo para suas coisas', 'Planeje as festas', 'Aproveite qualquer chance de descansar', 'Reserve dinheiro para compras'].map((tip, i) => <article key={tip}><span>0{i + 1}</span><h3>{tip}</h3></article>)}</div><div className="spanish"><p className="eyebrow">ESPANHOL DE EMERGÊNCIA</p><details><summary>¿Cuánto cuesta?</summary><p>Quanto custa?</p></details><details><summary>¿Dónde está el baño?</summary><p>Onde fica o banheiro?</p></details></div></section>
    <Budget />
    <section id="galeria" className="gallery section"><p className="eyebrow">08 — ARQUIVO VIVO</p><h2>100 momentos que<br />não couberam na revista</h2><p className="intro">Uma seleção de fotografias reais da viagem. Toque em qualquer uma para entrar na história.</p><div className="mosaic">{Array.from({ length: 100 }, (_, i) => <button key={i} onClick={() => setPhoto(i)}><img src={image(i + 1)} loading="lazy" decoding="async" alt={`Foto ${i + 1} da viagem para Bariloche`} /></button>)}</div></section>
    <Passport />
    <footer id="fechamento"><img src={image(100)} loading="lazy" alt="Grupo no encerramento da viagem" /><div><p className="eyebrow">FIM DA EDIÇÃO Nº 1</p><h2>O que fica quando<br />a viagem termina</h2><p>Não só fotos: uma coleção de dias que continuam sendo contados depois da volta.</p><strong>PANORAMA</strong><small>UM OLHAR ALÉM DO ÓBVIO<br />Editora Epifania · Instituto J&F Germinare Tech · Agosto de 2026</small></div></footer>
  </main>{photo !== null && <Lightbox index={photo} close={() => setPhoto(null)} />}</>;
}
