import { useEffect, useMemo, useState } from 'react';
import { chapters, credits, galleryGroups, image, quiz, spanish, timeline, tips } from './data/edition';

const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });

function Masthead() {
  const [compact, setCompact] = useState(false);
  const [progress, setProgress] = useState(0);
  useEffect(() => {
    const update = () => { setCompact(scrollY > 80); setProgress(Math.round(scrollY / Math.max(1, document.body.scrollHeight - innerHeight) * 100)); };
    update(); addEventListener('scroll', update, { passive: true }); return () => removeEventListener('scroll', update);
  }, []);
  return <header className={`masthead ${compact ? 'compact' : ''}`}>
    <button className="wordmark" onClick={() => scrollTo('capa')} aria-label="Voltar à capa">PANORAMA</button>
    <nav aria-label="Navegação principal"><button onClick={() => scrollTo('sumario')}>SUMÁRIO</button><button onClick={() => scrollTo('galeria')}>100 FOTOS</button></nav>
    <span className="edition">BARILOCHE <i>2026</i></span><div className="reading-progress" style={{ transform: `scaleX(${progress / 100})` }} />
  </header>;
}

function Lightbox({ index, close }: { index: number; close: () => void }) {
  const [current, setCurrent] = useState(index);
  useEffect(() => { const keys = (e: KeyboardEvent) => { if (e.key === 'Escape') close(); if (e.key === 'ArrowRight') setCurrent(v => (v + 1) % 100); if (e.key === 'ArrowLeft') setCurrent(v => (v + 99) % 100); }; const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; addEventListener('keydown', keys); return () => { document.body.style.overflow = previous; removeEventListener('keydown', keys); }; }, [close]);
  return <div className="lightbox" role="dialog" aria-modal="true" aria-label="Visualizador de fotos" onMouseDown={close}><button className="close" onClick={close} autoFocus>FECHAR ×</button><button className="arrow left" onMouseDown={e => e.stopPropagation()} onClick={() => setCurrent(v => (v + 99) % 100)} aria-label="Foto anterior">←</button><figure onMouseDown={e => e.stopPropagation()}><img src={image(current + 1)} alt={`Registro da viagem a Bariloche, foto ${current + 1} de 100`} /><figcaption>{String(current + 1).padStart(3, '0')} / 100 — Bariloche 2026</figcaption></figure><button className="arrow right" onMouseDown={e => e.stopPropagation()} onClick={() => setCurrent(v => (v + 1) % 100)} aria-label="Próxima foto">→</button></div>;
}

function Budget() {
  const [money, setMoney] = useState(1850); const [days, setDays] = useState(9); const [rate, setRate] = useState(260); const [reserve, setReserve] = useState(400); const [fixed, setFixed] = useState(650);
  const free = Math.max(0, money - reserve - fixed); const converted = free * rate;
  return <section id="matematica" className="math section"><p className="eyebrow">07 — PLANEJAMENTO, CÂMBIO E GASTOS</p><h2>Matemática<br />da viagem</h2><div className="math-feature"><div><span className="math-number">R$ 1.850</span><p>Na edição impressa: R$ 800 para gastos livres, R$ 400 de reserva e R$ 650 para taxas e uma atividade extra.</p><div className="bar"><b style={{ width: '43%' }}>LIVRE</b><b style={{ width: '22%' }}>RESERVA</b><b style={{ width: '35%' }}>TAXAS</b></div></div><div className="equation">R$ 800 × 260<br /><strong>= 208.000 pesos</strong><br /><small>208.000 ÷ 9 ≈ 23.111 pesos/dia</small></div></div><div className="math-insights"><article><span>60%</span><p>de economia estimada ao dividir a chapelaria de sete festas entre cinco pessoas.</p></article><article><span>G(d)</span><p>= 23.111,11 × d — uma função simples para acompanhar o gasto acumulado.</p></article></div><div className="simulator"><div><p className="eyebrow">E SE FOSSE A SUA VIAGEM?</p><h3>Monte seu cenário.</h3><label>Orçamento total <output>R$ {money.toLocaleString('pt-BR')}</output><input type="range" min="500" max="8000" step="50" value={money} onChange={e => setMoney(+e.target.value)} /></label><label>Dias <output>{days}</output><input type="range" min="3" max="15" value={days} onChange={e => setDays(+e.target.value)} /></label><label>Cotação peso/real <input aria-label="Cotação peso por real" value={rate} type="number" min="0" onChange={e => setRate(+e.target.value || 0)} /></label><label>Reserva <input aria-label="Reserva em reais" value={reserve} type="number" min="0" onChange={e => setReserve(+e.target.value || 0)} /></label><label>Taxas e atividades <input aria-label="Taxas e atividades em reais" value={fixed} type="number" min="0" onChange={e => setFixed(+e.target.value || 0)} /></label></div><div className="result" aria-live="polite"><span>ORÇAMENTO LIVRE</span><strong>R$ {free.toLocaleString('pt-BR')}</strong><span>CONVERTIDO</span><strong>{converted.toLocaleString('pt-BR')} pesos</strong><span>MÉDIA POR DIA</span><strong>{Math.round(converted / days).toLocaleString('pt-BR')} pesos</strong><small>Os 260 pesos por real são uma referência histórica da viagem, não uma cotação atual.</small></div></div></section>;
}

function Passport() {
  const [answers, setAnswers] = useState<number[]>(() => { try { return JSON.parse(localStorage.getItem('panorama-passport') || '[]'); } catch { return []; } });
  const done = answers.filter(answer => Number.isInteger(answer)).length; const profile = useMemo(() => answers.filter(n => n === 1).length >= 3 ? ['EXPLORADOR DA NEVE', 'Acordaria cedo mesmo depois de dormir pouco. Se tem frio, teleférico ou montanha, você está dentro.'] : answers.filter(n => n === 0).length >= 3 ? ['CAÇADOR DE MEMÓRIAS', 'Seu armazenamento acabaria antes da viagem — e você saberia exatamente onde todo mundo estava em cada momento.'] : ['GUIA NÃO OFICIAL', 'Você lê o cronograma, organiza os amigos e ainda lembra alguém de levar o casaco.']);
  const pick = (q: number, option: number) => { const next = [...answers]; next[q] = option; setAnswers(next); localStorage.setItem('panorama-passport', JSON.stringify(next)); };
  const share = async () => { const text = `Meu perfil em Bariloche é ${profile[0]} — PANORAMA 2026`; if (navigator.share) await navigator.share({ title: 'Passaporte Panorama', text }); else await navigator.clipboard?.writeText(text); };
  return <section id="passaporte" className="passport section"><p className="eyebrow">09 — PASSAPORTE PANORAMA <span>{done}/5</span></p><h2>Que tipo de viajante<br />você seria?</h2><p className="intro">Cinco escolhas, feitas só aqui no seu navegador. Sem login, sem coleta.</p><div className="passport-grid">{quiz.map(([question, options], q) => <fieldset key={question}><legend>{String(q + 1).padStart(2, '0')} — {question}</legend>{options.map((option, i) => <button key={option} className={answers[q] === i ? 'selected' : ''} onClick={() => pick(q, i)}>{String.fromCharCode(65 + i)} — {option}</button>)}</fieldset>)}</div>{done === 5 && <div className="profile"><p>SEU PASSAPORTE</p><h3>{profile[0]}</h3><p>{profile[1]}</p><button onClick={share}>COMPARTILHAR MEU PERFIL ↗</button><button onClick={() => { setAnswers([]); localStorage.removeItem('panorama-passport'); }}>REFAZER</button></div>}</section>;
}

export default function App() {
  const [photo, setPhoto] = useState<number | null>(null); const [preview, setPreview] = useState<number | null>(null); const [openDay, setOpenDay] = useState<number | null>(null);
  return <><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><Masthead /><main id="conteudo">
    <section id="capa" className="hero"><img src={image(17)} fetchPriority="high" alt="Montanhas nevadas de Bariloche sob um céu nublado" /><div className="hero-copy"><p>EDITORA EPIFANIA · AGOSTO 2026 · EDIÇÃO Nº 1</p><h1>BARILOCHE</h1><h2>Por que sua formatura merece essa viagem</h2><div className="hero-actions"><button onClick={() => scrollTo('sumario')}>COMEÇAR A LEITURA ↓</button><a href="/PANORAMA-Bariloche-2026.pdf" download>BAIXAR A EDIÇÃO EM PDF ↓</a></div></div><p className="hero-footer">UMA VIAGEM. CINCO OLHARES. NOVE DIAS. HISTÓRIAS DEMAIS PARA CABER NO PAPEL.</p></section>
    <section id="sumario" className="contents section"><p className="eyebrow">A EDIÇÃO</p><h2>Sumário</h2><div onMouseLeave={() => setPreview(null)}>{chapters.map(([n, title, desc, id], i) => <button key={id} onClick={() => scrollTo(id)} onMouseEnter={() => setPreview((i * 11) % 100)}><span>{n}</span><strong>{title}</strong><small>{desc}</small></button>)}</div>{preview !== null && <img className="contents-preview" src={image(preview + 1)} alt="" aria-hidden="true" />}</section>
    <section id="editorial" className="editorial section"><p className="eyebrow">01 — ABERTURA</p><h2>Editorial</h2><div className="editorial-text"><p>Panorama foi criada por cinco estudantes do 3º ano do ensino médio técnico da Germinare TECH. Nesta edição, a lente crítica se volta para uma experiência íntima e coletiva: a viagem de formatura.</p><p>Bariloche é neve, festa e fotografia, mas não é só isso. Por trás do roteiro existe um rito de passagem: nove dias para dividir custos, lidar com imprevistos, conviver 24 horas por dia e perceber que um ciclo está terminando.</p><p>Esta edição cruza relato pessoal, escolhas de consumo e matemática para mostrar que até a viagem mais esperada da vida escolar é uma lição prática de autonomia e decisão.</p></div><aside><p>CRÉDITOS DA EDIÇÃO</p>{credits.map(([role, name]) => <div className="credit" key={role}><small>{role}</small><span>{name}</span></div>)}</aside></section>
    <article id="materia" className="feature"><div className="feature-heading"><p className="eyebrow">02 — REPORTAGEM PRINCIPAL</p><h2>Olhares diferentes<br />da mesma viagem</h2><div className="deck"><p>A Panorama reuniu relato, crítica e números para contar o que Bariloche revelou sobre a turma — e sobre cada um de nós.</p><small>POR EQUIPE REVISTA PANORAMA · INSTITUTO J&amp;F</small></div></div><figure className="bleed"><img src={image(4)} alt="Turma reunida em uma praça de Bariloche" loading="lazy" /><figcaption>Nove dias de convivência transformaram o encerramento do Ensino Médio.</figcaption></figure><div className="longread"><p>Em julho de 2026, alunos do terceiro ano viajaram com a Travel Rock para San Carlos de Bariloche, na Argentina, em uma viagem de formatura antecipada. Passeios na neve, festas, caminhadas pela cidade e a convivência fora da escola transformaram o encerramento do Ensino Médio em uma experiência de autonomia e fortalecimento dos vínculos.</p><p>O roteiro reunia Cerro Catedral, Piedras Blancas, atividades extras e noites de festa. Os relatos, porém, mostram que cada estudante viveu a programação de forma diferente. As escolhas, quedas, conversas e improvisos deram significado ao que havia sido planejado.</p><p>O resultado não esconde o cansaço, os gastos fora do previsto ou as pequenas tensões de uma convivência ininterrupta. É justamente aí — e não só nas paisagens nevadas — que mora o relato verdadeiro de uma viagem de formatura.</p></div><blockquote>“A viagem deixou de ser uma lista de atrações: os intervalos também viraram história.”</blockquote><div className="two-images"><img src={image(19)} loading="lazy" alt="Estudante diante do lago e das montanhas" /><div><p className="eyebrow">FESTA, CANSAÇO E FIM DE ETAPA</p><p>A experiência foi marcante sem ser perfeita. Seu valor esteve em tirar a turma do contexto habitual e transformar esperas, quartos compartilhados, escolhas e risadas em memória de despedida.</p></div><img src={image(39)} loading="lazy" alt="Grupo de amigos agasalhados durante a viagem" /></div></article>
    <section id="cidade" className="city section"><p className="eyebrow">03 — BARILOCHE ALÉM DA NEVE</p><h2>O estrangeiro começa<br />nos detalhes.</h2><img src={image(57)} loading="lazy" alt="Vista do lago Nahuel Huapi" /><div className="city-notes">{[['NA RUA', 'Mitre, vitrines e a liberdade de escolher onde entrar.'], ['NA COMIDA', 'Café quente, chocolate e um croissant entre caminhadas.'], ['NO LAGO', 'Nahuel Huapi apareceu azul quando o céu finalmente abriu.'], ['NO QUARTO', 'Sete pessoas, um banheiro e histórias que não cabem em cronograma.']].map(([title, text]) => <div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section id="dias" className="timeline section"><p className="eyebrow">04 — CRONOLOGIA</p><h2>Nove dias<br />em Bariloche</h2><p className="intro">Nove dias, muitas histórias e uma viagem que passou rápido demais.</p><ol>{timeline.map(([day, title, text, img], i) => <li key={day}><button onClick={() => setOpenDay(openDay === i ? null : i)} aria-expanded={openDay === i}><span>DIA {day}</span><h3>{title}</h3><p>{text}</p><b>{openDay === i ? 'FECHAR −' : 'VER MAIS + '}</b></button>{openDay === i && <div className="day-detail"><img src={image(img)} alt={`Foto do dia ${day}`} loading="lazy" /><p>Um registro da viagem para acompanhar este capítulo. As histórias seguem em fotos, conversas e memórias compartilhadas.</p></div>}</li>)}</ol></section>
    <section id="roteiro" className="reality section"><p className="eyebrow">05 — O QUE O ROTEIRO NÃO CONTA</p><h2>Expectativa<br /><i>×</i> realidade</h2><div>{[['DESCANSO', '“Vou descansar e aproveitar tudo.”', 'Passeios de dia e festas à noite deixavam pouco espaço para dormir.'], ['NEVE', '“Vai ser só bonito.”', 'É bonita, sim. E também molhada, fria e ótima para cair.'], ['FESTAS', '“Vou só dar uma passada.”', 'A preparação no quarto já era parte da festa.'], ['ROTEIRO', '“Vou seguir tudo certinho.”', 'Os melhores momentos também apareciam nos intervalos.']].map(([title, expectation, reality]) => <details key={title}><summary><span>{title}</span><strong>EXPECTATIVA</strong><p>{expectation}</p></summary><div><strong>REALIDADE</strong><p>{reality}</p></div></details>)}</div></section>
    <section id="guia" className="guide section"><p className="eyebrow">06 — SERVIÇO</p><h2>Guia de sobrevivência<br />em Bariloche</h2><p className="intro">O que gostaríamos de saber antes de embarcar — sem fingir que cada detalhe pode ser controlado.</p><div className="tips">{tips.map(([title, text], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="spanish"><p className="eyebrow">ESPANHOL DE EMERGÊNCIA</p>{spanish.map(([phrase, translation]) => <details key={phrase}><summary>{phrase}</summary><p>{translation}</p></details>)}</div></section>
    <Budget />
    <section id="galeria" className="gallery section"><p className="eyebrow">08 — ARQUIVO VIVO</p><h2>100 momentos<br />em Bariloche</h2><p className="intro">A curadoria da revista reorganizada em oito capítulos visuais. Toque em qualquer foto para ampliar.</p><div className="gallery-index" aria-label="Capítulos da galeria">{galleryGroups.map(([title, , start, end]) => <a key={title} href={`#fotos-${start}`}>{title}<span>{end - start + 1}</span></a>)}</div>{galleryGroups.map(([title, description, start, end], group) => <section className="photo-chapter" id={`fotos-${start}`} key={title}><header><p>{String(group + 1).padStart(2, '0')} / 08</p><h3>{title}</h3><span>{description}</span></header><div className="mosaic">{Array.from({ length: end - start + 1 }, (_, offset) => { const n = start + offset; return <button key={n} onClick={() => setPhoto(n - 1)} aria-label={`Abrir foto ${n} de 100`}><img src={image(n)} loading="lazy" decoding="async" alt={`Foto ${n}: ${title.toLowerCase()} em Bariloche`} /><span>{String(n).padStart(3, '0')}</span></button>; })}</div></section>)}</section>
    <Passport />
    <footer id="fechamento"><img src={image(1)} loading="lazy" alt="Turma reunida com a bandeira do Brasil diante das montanhas" /><div><p className="eyebrow">FIM DA EDIÇÃO Nº 1</p><h2>O que fica quando<br />a viagem termina</h2><p>As malas voltaram mais cheias e as galerias, lotadas. Mas algumas coisas não cabem em fotografias: as conversas, as piadas e a sensação de viver juntos algo que não se repetirá da mesma forma.</p><strong>PANORAMA</strong><small>UM OLHAR ALÉM DO ÓBVIO<br />Editora Epifania · Instituto J&amp;F Germinare Tech · Agosto de 2026</small></div></footer>
  </main>{photo !== null && <Lightbox index={photo} close={() => setPhoto(null)} />}</>;
}
